import React, { useState } from 'react';
import { useNavigate } from 'react-router-dom';
import { login } from '../apiExtra';

const SignInPage: React.FC = () => {
  const navigate = useNavigate();
  const [form, setForm] = useState({ username: '', password: '' });
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState('');
  const [showPassword, setShowPassword] = useState(false);

  // Password strength is not shown — passwords are generated by the administrator.
  const checkPasswordRequirements = (password: string) => ({
    minLength: password.length >= 8,
    hasUppercase: /[A-Z]/.test(password),
    hasLowercase: /[a-z]/.test(password),
    hasNumber: /\d/.test(password),
    hasSpecial: /[!@#$%^&*()_+\-=\[\]{};':"\\|,.<>\/?]/.test(password),
  });

  const handleChange = (e: React.ChangeEvent<HTMLInputElement>) => {
    setForm({ ...form, [e.target.name]: e.target.value });
  };

  const handleSubmit = async (e: React.FormEvent) => {
    e.preventDefault();
    setLoading(true);
    setError('');
    try {
      const res = await login(form.username, form.password);
      localStorage.setItem('authToken', res.token);
      localStorage.setItem('userRole', res.user.role || 'invigilator');
      localStorage.setItem('username', res.user.username || res.user.email);
      localStorage.setItem('email', res.user.email);
      navigate('/dashboard');
    } catch (err: any) {
      setError(err.message || 'Invalid credentials');
    }
    setLoading(false);
  };

  return (
    <>
      <style>{`
        @media (max-width: 768px) {
          .signin-container {
            display: flex !important;
            flex-direction: column !important;
            height: 100vh !important;
            width: 100% !important;
          }
          .signin-sidebar {
            display: none !important;
            flex: 0 !important;
          }
          .signin-form-wrapper {
            flex: 1 !important;
            height: auto !important;
            min-height: 100vh !important;
            width: 100% !important;
          }
        }
      `}</style>
      <div className="signin-container page-enter" style={{ display: 'flex', height: '100vh', width: '100%', fontFamily: 'Inter, ui-sans-serif, system-ui, sans-serif' }}>
        {/* Left Side - Image */}
        <div className="signin-sidebar" style={{
          flex: 1,
          backgroundImage: "url('/UPSA.jpeg')",
          backgroundSize: 'cover',
          backgroundPosition: 'center',
          position: 'relative',
          display: 'flex',
          alignItems: 'center',
          justifyContent: 'center',
          minWidth: 0,
          transition: 'filter 0.6s ease',
        }}
        onMouseEnter={(e) => { e.currentTarget.style.filter = 'brightness(1.15)'; }}
        onMouseLeave={(e) => { e.currentTarget.style.filter = 'brightness(1)'; }}>
          <div style={{
            position: 'absolute', top: 0, left: 0, right: 0, bottom: 0,
            backgroundColor: 'rgba(2,27,75,0.78)',
            display: 'flex', flexDirection: 'column', justifyContent: 'center', alignItems: 'center', color: '#F8FAFC'
          }}>
            <h1 className="animate-fade-in-up delay-1" style={{ fontSize: '3rem', fontWeight: 'bold', marginBottom: '1rem' }}>Welcome</h1>
            <p className="animate-fade-in-up delay-3" style={{ fontSize: '1.2rem', fontStyle: 'italic' }}>"Scholarship with Professionalism"</p>
          </div>
        </div>

        {/* Right Side - Form */}
        <div className="signin-form-wrapper" style={{ flex: 1, display: 'flex', alignItems: 'center', justifyContent: 'center', backgroundColor: 'var(--bg)', minWidth: 0 }}>
          <div className="animate-scale-in delay-2" style={{ width: '100%', maxWidth: '400px', padding: '2.5rem', backgroundColor: 'var(--card)', borderRadius: '16px', boxShadow: '0 8px 24px rgba(0,0,0,0.35)', border: '1px solid var(--border)', borderTop: '3px solid var(--upsa-navy)', color: 'var(--text)', transition: 'box-shadow 0.3s ease, border-color 0.3s ease' }}
          onMouseEnter={(e) => { e.currentTarget.style.borderColor = 'rgba(255,182,6,0.25)'; e.currentTarget.style.boxShadow = '0 12px 32px rgba(0,0,0,0.45), 0 0 24px rgba(255,182,6,0.06)'; }}
          onMouseLeave={(e) => { e.currentTarget.style.borderColor = 'var(--border)'; e.currentTarget.style.boxShadow = '0 8px 24px rgba(0,0,0,0.35)'; }}>
          <h2 className="animate-fade-in-up delay-3" style={{ fontSize: '2rem', fontWeight: 700, color: 'var(--accent)', marginBottom: '0.5rem', textAlign: 'center' }}>Sign In</h2>
          <p className="animate-fade-in-up delay-4" style={{ color: 'var(--muted)', textAlign: 'center', marginBottom: '2rem' }}>Access your dashboard</p>
          
          <form onSubmit={handleSubmit} autoComplete="off">
            <div className="animate-fade-in-up delay-5" style={{ marginBottom: '1.25rem' }}>
              <label style={{ display: 'block', marginBottom: '0.5rem', color: 'var(--text-secondary)', fontWeight: 600 }}>Email</label>
              <input type="email" name="username" value={form.username} onChange={handleChange} placeholder="Enter your email" autoComplete="off" className="input" required />
            </div>
            <div className="animate-fade-in-up delay-6" style={{ marginBottom: '1.25rem' }}>
              <label style={{ display: 'block', marginBottom: '0.5rem', color: 'var(--text-secondary)', fontWeight: 600 }}>Password</label>
              <div style={{ position: 'relative', marginBottom: '0.5rem' }}>
                <input type={showPassword ? 'text' : 'password'} name="password" value={form.password} onChange={handleChange} placeholder="Enter your password" className="input" style={{ paddingRight: '2.5rem' }} required />
                <button type="button" onClick={() => setShowPassword(!showPassword)} style={{ position: 'absolute', right: '0.75rem', top: '50%', transform: 'translateY(-50%)', background: 'none', border: 'none', cursor: 'pointer', color: 'var(--muted)', fontSize: '1.2rem' }}>
                  {showPassword ? '👁️' : '👁️‍🗨️'}
                </button>
              </div>
              {form.password && (
                <div style={{ marginTop: '0.5rem' }}>
                </div>
              )}
            </div>
            {error && <div style={{ color: 'var(--upsa-danger)', marginBottom: '1rem', textAlign: 'center', animation: 'fadeIn 0.3s ease-out' }}>{error}</div>}
            <button type="submit" disabled={loading} className="btn btn-primary animate-fade-in-up delay-7" style={{ width: '100%', justifyContent: 'center', fontSize: '1rem', padding: '0.875rem' }}>
              {loading ? 'Signing In...' : 'Sign In'}
            </button>
          </form>
          <p className="animate-fade-in-up delay-8" style={{ textAlign: 'center', marginTop: '1.5rem', color: 'var(--muted)', fontSize: '0.85rem' }}>
            Invigilator access only. Sign in with the email and password provided by your administrator.
          </p>
        </div>
      </div>
    </div>
    </>
  );
};

export default SignInPage;